CREATE DATABASE IF NOT EXISTS DB_NAME;

CREATE TABLE IF NOT EXISTS DB_NAME.posts (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    body VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );
